# syntax=docker/dockerfile:experimental
FROM node:12.16.1-alpine3.11

WORKDIR /app

COPY package*.json /app

RUN --mount=type=cache,target=/app/node_modules \
    --mount=type=cache,target=/root/.npm \
    npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]
