version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules:
