version: "3.7"
services:
  react-dev:
    build:
      dockerfile: Dockerfile-dev
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm start
    ports:
      - "3000:3000"

volumes:
  node_modules:
